### ISSUE TITLE
Correct this please filter values incorrect

### ISSUE THREAD

**Issue by rgnarok** [rgnarok/CKP#18]
<img width="317" alt="image" src="https://github.com/rgnarok/CKP/assets/85341053/21a08ad7-b7c4-4986-b0bb-72d3ffcb655c">

**Comment by KamboSukhdeep** [comment]
@MaroofTech please remove dummy values from front end. 

@rgnarok In actual case it will return whatever is inserted in the database. 

Please provide me values so I can insert.

**Comment by rgnarok** [comment]
Newly added type, H, HAM
@KamboSukhdeep these were the details shared by the client >> they are sharing fetch it from spot tracker of the task

**Comment by KamboSukhdeep** [comment]
@rgnarok FYI - You shared the values with me which is currently reflecting in drop down. We will discuss it in our call today and update on the fly.

![image](https://github.com/rgnarok/CKP/assets/17181150/ae5d88b3-0aa0-407c-90c4-29a541491225)
