### ISSUE TITLE
Search should be same as PPT in user rights and roles

### ISSUE THREAD

**Issue by MaroofTech** [rgnarok/CKP#30]
![Screenshot (142)](https://github.com/user-attachments/assets/78fa7c1c-2bb2-42f5-a76b-a6bca4c50f01)

**Comment by vayuzpriya** [comment]
![image](https://github.com/user-attachments/assets/e7eb6739-4e8f-4719-b2e0-387c7e9e9f1d)
![image](https://github.com/user-attachments/assets/99c4be85-363e-4489-8930-3b8bacebddf4)
